server {
  listen 443 ssl; # Listen on port 443 for HTTPS
  ssl_certificate /etc/letsencrypt/live/vault.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/vault.example.com/privkey.pem;

  server_name vault.example.com;

  location / {
    proxy_hide_header X-Powered-By;

    proxy_pass http://127.0.0.1:5090;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 24h;  # Prevents Nginx from killing idle client connections
  }
}
